version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Google.Protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: Grpc.Auth
    versions:
    - 2.35.0
    - 2.36.0
    - 2.36.1
    - 2.36.4
  - dependency-name: Grpc.Core.Api
    versions:
    - 2.35.0
    - 2.36.0
    - 2.36.1
    - 2.36.4
  - dependency-name: Google.Apis.Translate.v2
    versions:
    - 1.49.0.875
    - 1.50.0.875
  - dependency-name: Google.Apis.Auth
    versions:
    - 1.49.0
    - 1.50.0
  - dependency-name: Google.Api.CommonProtos
    versions:
    - 2.2.0
